import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/service/theme.context";
import LayoutWrapper from "@/components/layoutWrapper";
import { QuizContextProvider } from "@/service/quiz.context";

const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} overflow-hidden relative`}>
        <ThemeContextProvider>
          <QuizContextProvider>
            <LayoutWrapper>{children}</LayoutWrapper>
          </QuizContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
